version: '3.1'

services:

  wdp:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: user
      WORDPRESS_DB_NAME: mysql_wdpDB
    volumes:
      - wdp:/var/www/html

  db:
    image: mysql:5.7.20
    restart: always
    environment:
      MYSQL_DATABASE: mysql_wdpDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wdp:
  db: